import { parasFooterAtheneum } from "../features/atheneum/translations";
import { parasFooterOutbrain } from "../features/outbrain/translations";
import { parasFooterReadyForMail } from "../features/ready-for-email/translations";
import type { FooterTranslations } from "../types/footer";
import type { TranslationsType } from "../types/translations";

export default function footerTranslations(
  brandName: string
): FooterTranslations {
  const classic: TranslationsType = {
    en: `<p>Trading carries a high level of risk to your capital due to the volatility of the underlying market. Trading is not suitable for everyone and may result in you losing all your investment. ${brandName} products may not be suitable for all investors. Therefore, you should ensure that you understand the risks and seek advice from an independent and suitably licensed financial advisor.</p>`,
    it: `<p>Il trading ha un elevato livello di rischio per il capitale a causa della volatilità del mercato. Il trading non è adatto a tutti e può causare la perdita di tutto il tuo investimento. I segnali ${brandName} potrebbero non essere adatti a tutti gli investitori. Pertanto, è necessario assicurarsi di comprendere i rischi e richiedere consulenza da un consulente finanziario indipendente e adeguatamente autorizzato.</p>`,
    tr: `<p>Alım satım, temel piyasanın oynaklığı nedeniyle sermayeniz için yüksek düzeyde risk taşır. Alım satım herkes için uygun değildir ve tüm yatırımınızı kaybetmenize neden olabilir. ${brandName} ürünleri tüm yatırımcılar için uygun olmayabilir. Bu nedenle, riskleri anladığınızdan emin olmalı ve bağımsız ve uygun şekilde lisanslanmış bir finansal danışmandan tavsiye almalısınız.</p>`,
    ro: `<p>Tranzacționarea implică un nivel ridicat de risc pentru capitalul dumneavoastră din cauza volatilității pieței subiacente. Tranzacționarea nu este potrivită pentru toată lumea și poate duce la pierderea tuturor investițiilor. Este posibil ca produsele ${brandName} să nu fie potrivite pentru toți investitorii. Prin urmare, ar trebui să vă asigurați că înțelegeți riscurile și că solicitați sfatul unui consilier financiar independent și autorizat corespunzător.</p>`,
    ar: `<p>التداول ينطوي على مستوى عالٍ من المخاطر على رأس مالك بسبب تقلبات السوق الأساسية. التداول غير مناسب للجميع وقد يؤدي إلى خسارة استثمارك بالكامل. قد لا تكون منتجات ${brandName} مناسبة لجميع المستثمرين. لذلك، يجب عليك التأكد من فهمك للمخاطر وطلب المشورة من مستشار مالي مستقل ومرخص بشكل مناسب.</p>`,
    de: `<p>Der Handel birgt aufgrund der Volatilität des zugrunde liegenden Marktes ein hohes Risiko für Ihr Kapital. Der Handel ist nicht für jeden geeignet und kann dazu führen, dass Sie Ihr gesamtes Investment verlieren. ${brandName}-Produkte sind möglicherweise nicht für alle Anleger geeignet. Daher sollten Sie sicherstellen, dass Sie die Risiken verstehen und den Rat eines unabhängigen und entsprechend lizenzierten Finanzberaters einholen.</p>`,
    es: `<p>El comercio tiene un alto nivel de riesgo para el capital debido a la volatilidad del mercado. El comercio no es adecuado para todos y puede hacer que pierda toda su inversión. Las señales de ${brandName} pueden no ser adecuadas para todos los inversores. Por lo tanto, debe asegurarse de comprender los riesgos y buscar el asesoramiento de un asesor financiero independiente y debidamente autorizado.</p>`,
    sv: `<p>Handel innebär en hög risk för ditt kapital på grund av volatiliteten på den underliggande marknaden. Handel är inte lämpligt för alla och kan leda till att hela din investering går förlorad. ${brandName}-produkter kanske inte är lämpliga för alla investerare. Därför bör du se till att du förstår riskerna och be om råd från en oberoende och lämpligt licensierad finansiell rådgivare.</p>`,
    pt: `<p>O trading envolve um alto nível de risco para o seu capital devido à volatilidade do mercado subjacente. O trading não é adequado para todos e pode resultar na perda total do seu investimento. Os produtos ${brandName} podem não ser adequados para todos os investidores. Portanto, você deve garantir que compreende os riscos e buscar aconselhamento de um consultor financeiro independente e devidamente licenciado.</p>`,
    fi: `<p>Kaupankäynti sisältää korkean riskitason pääomallesi johtuen taustalla olevan markkinan volatiliteetista. Kaupankäynti ei sovi kaikille ja saattaa johtaa koko sijoituksesi menettämiseen. ${brandName}-tuotteet eivät välttämättä sovi kaikille sijoittajille. Siksi sinun tulisi varmistaa, että ymmärrät riskit ja hakea neuvoa itsenäiseltä ja asianmukaisesti lisensoidulta talousneuvojalle.</p>`,
    pl: `<p>Handel niesie ze sobą wysoki poziom ryzyka dla Twojego kapitału ze względu na zmienność rynku bazowego. Handel nie jest odpowiedni dla każdego i może doprowadzić do utraty wszystkich inwestycji. Produkty ${brandName} mogą nie być odpowiednie dla wszystkich traderów. Dlatego upewnij się, że rozumiesz ryzyko i zasięgnij porady niezależnego i odpowiednio licencjonowanego doradcy finansowego.</p>`,
    hu: `<p>A kereskedés magas kockázatot jelent a tőkédre nézve az alapul szolgáló piac volatilitása miatt. A kereskedés nem mindenki számára megfelelő, és az összes befektetésed elvesztéséhez vezethet. A ${brandName} termékek nem biztos, hogy minden befektető számára megfelelőek. Ezért győződj meg arról, hogy megérted a kockázatokat, és kérj tanácsot egy független és megfelelő engedéllyel rendelkező pénzügyi tanácsadótól.</p>`,
    th: `<p>การซื้อขายมีความเสี่ยงสูงต่อเงินทุนของคุณเนื่องจากความผันผวนของตลาด การซื้อขายไม่เหมาะสำหรับทุกคนและอาจทำให้คุณสูญเสียเงินลงทุนทั้งหมด ผลิตภัณฑ์ของ ${brandName} อาจไม่เหมาะสำหรับนักลงทุนทุกคน ดังนั้นคุณควรแน่ใจว่าคุณเข้าใจความเสี่ยงและขอคำแนะนำจากที่ปรึกษาทางการเงินอิสระที่ได้รับอนุญาตอย่างเหมาะสม</p>`,
    ms: `<p>Perdagangan membawa tahap risiko yang tinggi kepada modal anda kerana turun naik pasaran asas. Perdagangan tidak sesuai untuk semua orang dan boleh mengakibatkan kehilangan semua pelaburan anda. Produk ${brandName} mungkin tidak sesuai untuk semua pelabur. Oleh itu, anda harus memastikan bahawa anda memahami risiko dan mendapatkan nasihat daripada penasihat kewangan bebas yang berlesen dengan sewajarnya.</p>`,
    vi: `<p>Giao dịch mang lại mức độ rủi ro cao cho vốn của bạn do sự biến động của thị trường cơ sở. Giao dịch không phù hợp với tất cả mọi người và có thể dẫn đến mất toàn bộ khoản đầu tư của bạn. Sản phẩm của ${brandName} có thể không phù hợp với tất cả các nhà đầu tư. Do đó, bạn nên đảm bảo rằng bạn hiểu các rủi ro và tìm kiếm lời khuyên từ một cố vấn tài chính độc lập và được cấp phép phù hợp.</p>`,
  };

  const esma: TranslationsType = {
    en: `
      <p>CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. The vast majority of retail investor accounts lose money when trading CFDs. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.</p>
      <p>Engaging in the trading of financial instruments carries significant risks, including the potential loss of a portion or all of your invested capital. This activity may not be suitable for every investor. The prices of many financial instruments are highly volatile and can be influenced by external factors like financial, regulatory, or political events. Trading on margin amplifies the financial risks involved. Prior to making a decision to trade financial instruments or cryptocurrencies, it is important to be fully aware of the potential risks and costs associated with participating in financial markets. Take the time to carefully assess your investment objectives, level of experience, and risk tolerance. When necessary, seek professional advice to ensure informed decision-making.</p>`,
    it: `
      <p>I CFD sono strumenti complessi e comportano un alto rischio di perdere rapidamente denaro a causa della leva finanziaria. La stragrande maggioranza dei conti degli investitori al dettaglio perde denaro durante il trading di CFD. Dovresti considerare se comprendi come funzionano i CFD e se puoi permetterti di prendere il massimo rischio di perdere i tuoi soldi.</p>
      <p>La negoziazione di strumenti finanziari comporta rischi significativi, inclusa la potenziale perdita di una parte o di tutto il capitale investito. Questa attività potrebbe non essere adatta a tutti gli investitori. I prezzi di molti strumenti finanziari sono altamente volatili e possono essere influenzati da fattori esterni come eventi finanziari, normativi o politici. Il trading a margine amplifica i rischi finanziari coinvolti. Prima di prendere la decisione di negoziare strumenti finanziari o criptovalute, è importante essere pienamente consapevoli dei potenziali rischi e costi associati alla partecipazione ai mercati finanziari. Prenditi il tempo per valutare attentamente i tuoi obiettivi di investimento, il livello di esperienza e la tolleranza al rischio. Se necessario, cercare una consulenza professionale per garantire un processo decisionale informato.</p>`,
    tr: `
      <p>CFD'ler karmaşık enstrümanlardır ve kaldıraç nedeniyle hızla para kaybetme riski taşır. Perakende yatırımcı hesaplarının büyük çoğunluğu CFD ticareti yaparken para kaybetmektedir. CFD'lerin nasıl çalıştığını anlayıp anlamadığınızı ve paranızı kaybetme riskini alıp alamayacağınızı düşünmelisiniz.</p>
      <p>Finansal enstrümanların ticareti önemli riskler içerir, yatırım sermayenizin bir kısmını veya tamamını kaybetme olasılığı dahil. Bu faaliyet her yatırımcı için uygun olmayabilir. Birçok finansal enstrümanın fiyatları son derece dalgalıdır ve finansal, düzenleyici veya politik olaylar gibi dış faktörlerden etkilenebilir. Kaldıraçlı ticaret finansal riskleri artırır. Finansal enstrümanlar veya kripto para birimleri ile işlem yapma kararı vermeden önce, finansal piyasalara katılmanın potansiyel riskleri ve maliyetleri konusunda tam olarak bilinçli olmak önemlidir. Yatırım hedeflerinizi, deneyim seviyenizi ve risk toleransınızı dikkatlice değerlendirmek için zaman ayırın. Gerekirse bilinçli karar vermenizi sağlamak için profesyonel tavsiye alın.</p>`,
    ro: `
      <p>CFD-urile sunt instrumente complexe și prezintă un risc mare de a pierde bani rapid din cauza efectului de levier. Marea majoritate a conturilor de investitori de retail pierd bani atunci când tranzacționați CFD-uri. Ar trebui să vă gândiți dacă înțelegeți cum funcționează CFD-urile și dacă vă puteți permite riscul de a pierde banii.</p>
      <p>Angajarea în tranzacționarea instrumentelor financiare implică riscuri semnificative, inclusiv pierderea potențială a unei părți sau a întregului capital investit. Este posibil ca această activitate să nu fie potrivită pentru orice investitor. Prețurile multor instrumente financiare sunt foarte volatile și pot fi influențate de factori externi, cum ar fi evenimente financiare, de reglementare sau politice. Tranzacționarea cu marjă amplifică riscurile financiare implicate. Înainte de a lua o decizie de a tranzacționa instrumente financiare sau criptomonede, este important să fiți pe deplin conștient de potențialele riscuri și costuri asociate cu participarea la piețele financiare. Acordați-vă timp pentru a vă evalua cu atenție obiectivele de investiții, nivelul de experiență și toleranța la risc. Când este necesar, solicitați sfaturi profesionale pentru a asigura luarea deciziilor în cunoștință de cauză.</p>`,
    ar: `
      <p>العقود مقابل الفروقات هي أدوات معقدة وتنطوي على مخاطر عالية بخسارة الأموال بسرعة بسبب الرافعة المالية. تخسر الغالبية العظمى من حسابات المستثمرين الأفراد الأموال عند تداول العقود مقابل الفروقات. يجب عليك أن تفكر فيما إذا كنت تفهم كيفية عمل العقود مقابل الفروقات وما إذا كنت تستطيع تحمل مخاطر خسارة أموالك.</p>
      <p>إن التداول في الأدوات المالية ينطوي على مخاطر كبيرة، بما في ذلك الخسارة المحتملة لبعض أو كل رأس المال المستثمر. قد لا يكون هذا النشاط مناسبًا لكل مستثمر. إن أسعار العديد من الأدوات المالية متقلبة للغاية ويمكن أن تتأثر بعوامل خارجية، مثل الأحداث المالية أو التنظيمية أو السياسية. يؤدي التداول بالهامش إلى تضخيم المخاطر المالية المرتبطة به. قبل اتخاذ قرار بشأن تداول الأدوات المالية أو العملات المشفرة، من المهم أن تكون على دراية كاملة بالمخاطر والتكاليف المحتملة المرتبطة بالمشاركة في الأسواق المالية. خذ الوقت الكافي لتقييم أهدافك الاستثمارية ومستوى خبرتك وقدرتك على تحمل المخاطر بعناية. عند الضرورة، اطلب المشورة المتخصصة لضمان اتخاذ قرارات مستنيرة.</p>`,
    de: `
      <p>CFDs sind komplexe Finanzinstrumente und bergen ein hohes Risiko, aufgrund von Hebelwirkung schnell Geld zu verlieren. Die überwiegende Mehrheit der Konten von Kleinanlegern verliert beim Handel mit CFDs Geld. Sie sollten sich überlegen, ob Sie verstehen, wie CFDs funktionieren, und ob Sie sich das hohe Risiko eines Geldverlusts leisten können.</p>
      <p>Der Handel mit Finanzinstrumenten birgt erhebliche Risiken, einschließlich des möglichen Verlusts eines Teils oder des gesamten investierten Kapitals. Diese Tätigkeit ist möglicherweise nicht für jeden Anleger geeignet. Die Preise vieler Finanzinstrumente sind äußerst volatil und können durch externe Faktoren wie finanzielle, regulatorische oder politische Ereignisse beeinflusst werden. Der Margin-Handel verstärkt die damit verbundenen finanziellen Risiken. Bevor Sie eine Entscheidung über den Handel mit Finanzinstrumenten oder Kryptowährungen treffen, ist es wichtig, sich der potenziellen Risiken und Kosten bewusst zu sein. Nehmen Sie sich die Zeit, Ihre Anlageziele, Ihr Erfahrungsniveau und Ihre Risikotoleranz sorgfältig zu bewerten. Falls erforderlich, suchen Sie professionelle Beratung, um eine fundierte Entscheidung zu treffen.</p>`,
    es: `
      <p>Los CFD son instrumentos complejos y conllevan un alto riesgo de perder dinero rápidamente debido al apalancamiento. La gran mayoría de las cuentas de inversores minoristas pierden dinero al operar con CFD. Usted debe considerar si entiende cómo funcionan los CFDs y si puede permitirse asumir el alto riesgo de perder su dinero.</p>
      <p>La Comisión Nacional del Mercado de Valores de España (la "CNMV") ha determinado que, debido a la complejidad de los CFD y a los riesgos que conllevan, la compra de este tipo de producto por parte de Clientes Minoristas no es apropiada/adecuada. En este sentido, de conformidad con los requisitos pertinentes introducidos por la CNMV, se le advierte de que está a punto de adquirir un producto que es complejo y difícil de entender: Contratos por Diferencias (CFDs). La CNMV ha determinado que, debido a su complejidad y a los riesgos que entraña, la adquisición de este producto por inversores minoristas no es apropiada/adecuada.</p>
      <p>Participar en la negociación de instrumentos financieros conlleva riesgos significativos, incluida la posible pérdida de una parte o la totalidad del capital invertido. Esta actividad puede no ser adecuada para todos los inversores. Los precios de muchos instrumentos financieros son muy volátiles y pueden verse influidos por factores externos como acontecimientos financieros, normativos o políticos. Operar con margen amplifica los riesgos financieros. Antes de tomar la decisión de operar con instrumentos financieros o criptomonedas, es importante ser plenamente consciente de los posibles riesgos y costes asociados a la participación en los mercados financieros. Tómese su tiempo para evaluar cuidadosamente sus objetivos de inversión, su nivel de experiencia y su tolerancia al riesgo. Cuando sea necesario, busque asesoramiento profesional para garantizar una toma de decisiones informada.</p>`,
    sv: `
      <p>CFD:er är komplexa instrument och medför en hög risk att snabbt förlora pengar på grund av hävstångseffekten. De allra flesta konton för icke-professionella investerare förlorar pengar när de handlar med CFD:er. Du bör överväga om du förstår hur CFD:er fungerar och om du har råd att ta den höga risken att förlora dina pengar.</p>
      <p>Att delta i handel med finansiella instrument medför betydande risker, inklusive den potentiella förlusten av en del av eller hela ditt investerade kapital. Denna verksamhet kanske inte är lämplig för alla investerare. Priserna på många finansiella instrument är mycket volatila och kan påverkas av externa faktorer som finansiella, regulatoriska eller politiska händelser. Handel på marginal förstärker de finansiella riskerna. Innan du fattar ett beslut om att handla med finansiella instrument eller kryptovalutor är det viktigt att du är fullt medveten om de potentiella risker och kostnader som är förknippade med att delta på finansmarknaderna. Ta dig tid att noggrant utvärdera dina investeringsmål, din erfarenhetsnivå och din risktolerans. Sök vid behov professionell rådgivning för att säkerställa ett välgrundat beslutsfattande.</p>`,
    pt: `
      <p>Os CFDs são instrumentos complexos e apresentam um alto risco de perda rápida de dinheiro devido à alavancagem. A grande maioria das contas de investidores de varejo perde dinheiro ao negociar CFDs. Você deve considerar se entende como os CFDs funcionam e se pode arcar com o alto risco de perder seu dinheiro.</p>
      <p>A negociação de instrumentos financeiros envolve riscos significativos, incluindo a possível perda de parte ou da totalidade do capital investido. Essa atividade pode não ser adequada para todos os investidores. Os preços de muitos instrumentos financeiros são altamente voláteis e podem ser influenciados por fatores externos, como eventos financeiros, regulatórios ou políticos. A negociação com margem amplifica os riscos financeiros envolvidos. Antes de decidir negociar instrumentos financeiros ou criptomoedas, é importante estar plenamente ciente dos riscos potenciais e dos custos associados à participação nos mercados financeiros. Reserve um tempo para avaliar cuidadosamente seus objetivos de investimento, nível de experiência e tolerância ao risco. Se necessário, procure aconselhamento profissional para tomar decisões informadas.</p>`,
    fi: `
      <p>CFD:t ovat monimutkaisia instrumentteja ja niihin liittyy suuri riski menettää rahaa nopeasti vipuvaikutuksen vuoksi. Suurin osa yksityissijoittajien tileistä menettää rahaa käydessään kauppaa CFD:illä. Sinun tulisi harkita, ymmärrätkö, miten CFD:t toimivat, ja pystytkö ottamaan suuren riskin rahojen menettämisestä.</p>
      <p>Rahoitusvälineiden kaupankäynti sisältää merkittäviä riskejä, mukaan lukien mahdollinen sijoitetun pääoman osittainen tai täydellinen menetys. Tämä toiminta ei välttämättä sovi kaikille sijoittajille. Monien rahoitusvälineiden hinnat ovat erittäin epävakaita ja voivat vaikuttaa ulkoisista tekijöistä, kuten taloudellisista, sääntelyyn liittyvistä tai poliittisista tapahtumista. Vipukauppa lisää taloudellisia riskejä. Ennen päätöksentekoa rahoitusvälineiden tai kryptovaluuttojen kaupankäynnistä on tärkeää olla täysin tietoinen mahdollisista riskeistä ja kustannuksista, jotka liittyvät rahoitusmarkkinoille osallistumiseen. Käytä aikaa sijoitustavoitteidesi, kokemustasosi ja riskinsietokykysi huolelliseen arviointiin. Tarvittaessa hae ammattilaisen neuvoja varmistaaksesi tietoon perustuvan päätöksen.</p>`,
    pl: `
      <p>Kontrakty CFD są złożonymi instrumentami i wiążą się z wysokim ryzykiem szybkiej utraty pieniędzy z powodu dźwigni finansowej. Zdecydowana większość rachunków inwestorów detalicznych odnotowuje straty pieniężne podczas handlu kontraktami CFD. Powinieneś rozważyć, czy rozumiesz, jak działają kontrakty CFD i czy możesz sobie pozwolić na wysokie ryzyko utraty pieniędzy.</p>
      <p>Angażowanie się w handel instrumentami finansowymi niesie ze sobą znaczne ryzyko, w tym potencjalną utratę części lub całości zainwestowanego kapitału. Ta aktywność może nie być odpowiednia dla każdego inwestora. Ceny wielu instrumentów finansowych są bardzo zmienne i mogą na nie wpływać czynniki zewnętrzne, takie jak wydarzenia finansowe, regulacyjne lub polityczne. Handel na marży zwiększa związane z tym ryzyko finansowe. Przed podjęciem decyzji o handlu instrumentami finansowymi lub kryptowalutami ważne jest, aby być w pełni świadomym potencjalnych zagrożeń i kosztów związanych z uczestnictwem w rynkach finansowych. Poświęć trochę czasu, aby dokładnie ocenić swoje cele inwestycyjne, poziom doświadczenia i tolerancję ryzyka. W razie potrzeby zasięgnij profesjonalnej porady, aby zapewnić świadome podejmowanie decyzji.</p>`,
    hu: `
      <p>A CFD-k összetett pénzügyi eszközök, és a tőkeáttétel miatt nagy a pénzvesztés kockázata. A lakossági befektetői számlák túlnyomó többsége pénzt veszít a CFD-kereskedés során. Fontolja meg, hogy érti-e, hogyan működnek a CFD-k, és megengedheti-e magának a magas kockázatot, hogy elveszítheti a pénzét.</p>
      <p>A pénzügyi eszközök kereskedése jelentős kockázatokkal jár, beleértve a befektetett tőke egy részének vagy egészének elvesztését. Ez a tevékenység nem feltétlenül alkalmas minden befektető számára. Számos pénzügyi eszköz ára rendkívül ingadozó, és külső tényezők, például pénzügyi, szabályozási vagy politikai események befolyásolhatják. A tőkeáttételes kereskedés fokozza a pénzügyi kockázatokat. Mielőtt úgy döntene, hogy pénzügyi eszközökkel vagy kriptovalutákkal kereskedik, fontos, hogy teljes mértékben tisztában legyen a pénzügyi piacokon való részvétellel járó lehetséges kockázatokkal és költségekkel. Szánjon időt befektetési céljainak, tapasztalati szintjének és kockázattűrő képességének alapos értékelésére. Ha szükséges, kérjen szakmai tanácsot a megalapozott döntéshozatal érdekében.</p>`,
    th: `
      <p>CFD เป็นตราสารที่ซับซ้อนและมีความเสี่ยงสูงในการสูญเสียเงินอย่างรวดเร็วเนื่องจากเลเวอเรจ บัญชีนักลงทุนรายย่อยส่วนใหญ่สูญเสียเงินเมื่อทำการซื้อขาย CFD คุณควรพิจารณาว่าคุณเข้าใจวิธีการทำงานของ CFD และสามารถรับความเสี่ยงสูงในการสูญเสียเงินของคุณได้หรือไม่</p>
      <p>การซื้อขายเครื่องมือทางการเงินมีความเสี่ยงอย่างมาก รวมถึงโอกาสในการสูญเสียเงินลงทุนบางส่วนหรือทั้งหมด กิจกรรมนี้อาจไม่เหมาะสำหรับนักลงทุนทุกคน ราคาของเครื่องมือทางการเงินหลายชนิดมีความผันผวนสูง และอาจได้รับอิทธิพลจากปัจจัยภายนอก เช่น เหตุการณ์ทางการเงิน กฎระเบียบ หรือการเมือง การซื้อขายด้วยมาร์จิ้นเพิ่มความเสี่ยงทางการเงิน ก่อนตัดสินใจซื้อขายเครื่องมือทางการเงินหรือสกุลเงินดิจิทัล สิ่งสำคัญคือต้องตระหนักถึงความเสี่ยงและต้นทุนที่อาจเกิดขึ้นจากการมีส่วนร่วมในตลาดการเงิน ใช้เวลาในการประเมินวัตถุประสงค์การลงทุน ระดับประสบการณ์ และความสามารถในการรับความเสี่ยงของคุณอย่างรอบคอบ หากจำเป็น ควรขอคำแนะนำจากผู้เชี่ยวชาญเพื่อการตัดสินใจที่มีข้อมูลครบถ้วน</p>`,
    ms: `
      <p>CFD adalah instrumen kompleks dan membawa risiko tinggi kehilangan wang dengan cepat kerana leveraj. Majoriti akaun pelabur runcit kehilangan wang apabila berdagang CFD. Anda harus mempertimbangkan sama ada anda memahami bagaimana CFD berfungsi dan sama ada anda mampu mengambil risiko tinggi kehilangan wang anda.</p>
      <p>Perdagangan instrumen kewangan melibatkan risiko yang ketara, termasuk kemungkinan kehilangan sebahagian atau semua modal yang dilaburkan. Aktiviti ini mungkin tidak sesuai untuk setiap pelabur. Harga banyak instrumen kewangan sangat tidak menentu dan boleh dipengaruhi oleh faktor luaran seperti peristiwa kewangan, kawal selia, atau politik. Perdagangan dengan margin meningkatkan risiko kewangan yang terlibat. Sebelum membuat keputusan untuk berdagang instrumen kewangan atau mata wang kripto, adalah penting untuk mengetahui sepenuhnya risiko dan kos yang berpotensi berkaitan dengan penyertaan dalam pasaran kewangan. Luangkan masa untuk menilai dengan teliti objektif pelaburan anda, tahap pengalaman, dan toleransi risiko anda. Apabila perlu, dapatkan nasihat profesional untuk memastikan keputusan yang berinformasi.</p>`,
    vi: `
      <p>CFD là các công cụ phức tạp và có rủi ro cao mất tiền nhanh chóng do đòn bẩy. Phần lớn tài khoản nhà đầu tư nhỏ lẻ mất tiền khi giao dịch CFD. Bạn nên cân nhắc xem bạn có hiểu cách CFD hoạt động hay không và liệu bạn có đủ khả năng chấp nhận rủi ro mất tiền cao hay không.</p>
      <p>Giao dịch các công cụ tài chính tiềm ẩn rủi ro đáng kể, bao gồm khả năng mất một phần hoặc toàn bộ vốn đầu tư. Hoạt động này có thể không phù hợp với mọi nhà đầu tư. Giá của nhiều công cụ tài chính biến động mạnh và có thể bị ảnh hưởng bởi các yếu tố bên ngoài như sự kiện tài chính, quy định hoặc chính trị. Giao dịch ký quỹ làm tăng rủi ro tài chính liên quan. Trước khi quyết định giao dịch công cụ tài chính hoặc tiền điện tử, điều quan trọng là phải nhận thức đầy đủ về các rủi ro và chi phí tiềm ẩn liên quan đến việc tham gia vào thị trường tài chính. Dành thời gian để đánh giá cẩn thận mục tiêu đầu tư, mức độ kinh nghiệm và khả năng chịu rủi ro của bạn. Khi cần thiết, hãy tìm kiếm lời khuyên chuyên môn để đảm bảo quyết định được đưa ra một cách thông tin.</p>`,
  };

  const endorsed: TranslationsType = {
    en: `
      <p>Leveraged products such as CFDs and Forex are considered intricate financial assets and may not be suitable for all investors as they carry a high degree of risk and can lead to the loss of your investment. Before getting involved with trading, consider your financial goals, your skills and gage the possible risks associated with trading Company's Products. Independent advice might be sought.</p>
      <p>ORO FINTECH LIMITED is registered in Seychelles with registration number 8425077-1 and authorised by the Financial Services Authority (FSA) as Securities Dealer with license number SD046.</p>`,
    it: `
      <p>I prodotti a leva come i CFD e il Forex sono considerati strumenti finanziari complessi e potrebbero non essere adatti a tutti gli investitori, poiché comportano un alto grado di rischio e possono portare alla perdita del tuo investimento. Prima di intraprendere il trading, considera i tuoi obiettivi finanziari, le tue competenze e valuta i rischi potenziali associati al trading dei Prodotti della Società. Potresti richiedere un parere indipendente.</p>
      <p>ORO FINTECH LIMITED è registrata alle Seychelles con il numero di registrazione 8425077-1 ed è autorizzata dall'Autorità dei Servizi Finanziari (FSA) come Dealer di Titoli con numero di licenza SD046.</p>`,
    tr: `
      <p>Yatırımcılar için uygun olmayabilecek karmaşık finansal varlıklar olan CFD'ler ve Forex, yüksek risk taşıyan ürünlerdir ve yatırımınızın kaybına yol açabilir. İşleme girmeden önce, finansal hedeflerinizi, becerilerinizi göz önünde bulundurun ve Şirketin Ürünleriyle işlem yapmanın potansiyel risklerini değerlendirin. Bağımsız tavsiye alabilirsiniz.</p>
      <p>ORO FINTECH LIMITED, Seyşeller'de 8425077-1 kayıt numarasıyla kaydedilmiş ve Finansal Hizmetler Otoritesi (FSA) tarafından SD046 lisans numarasıyla Menkul Kıymetler Tüccarı olarak yetkilendirilmiştir.</p>`,
    ro: `
      <p>Produsele cu levier, cum ar fi CFD-urile și Forex, sunt considerate active financiare complexe și pot să nu fie potrivite pentru toți investitorii, deoarece implică un grad ridicat de risc și pot duce la pierderea investiției. Înainte de a vă implica în tranzacționare, luați în considerare obiectivele financiare, abilitățile și evaluați riscurile posibile asociate cu tranzacționarea produselor companiei. Puteți solicita sfaturi independente.</p>
      <p>ORO FINTECH LIMITED este înregistrată în Seychelles cu numărul de înregistrare 8425077-1 și autorizată de Autoritatea Serviciilor Financiare (FSA) ca Dealer de Titluri cu numărul de licență SD046.</p>`,
    ar: `
      <p>تعتبر المنتجات ذات الرفع المالي مثل عقود الفروقات والفوركس من الأصول المالية المعقدة وقد لا تكون مناسبة لجميع المستثمرين حيث تحمل درجة عالية من المخاطر وقد تؤدي إلى فقدان استثمارك. قبل المشاركة في التداول، ضع في اعتبارك أهدافك المالية ومهاراتك وقيّم المخاطر المحتملة المرتبطة بتداول منتجات الشركة. قد يُطلب استشارة مستقلة.</p>
      <p>شركة ORO FINTECH LIMITED مسجلة في سيشيل برقم التسجيل 8425077-1 ومعتمدة من قبل هيئة الخدمات المالية (FSA) كـ تاجر أوراق مالية برقم الترخيص SD046.</p>`,
    de: `
      <p>Hebelprodukte wie CFDs und Forex gelten als komplexe Finanzinstrumente und sind möglicherweise nicht für alle Anleger geeignet, da sie ein hohes Risiko bergen und zu einem Verlust Ihrer Investition führen können. Bevor Sie sich mit dem Handel beschäftigen, sollten Sie Ihre finanziellen Ziele, Ihre Fähigkeiten und die möglichen Risiken des Handels mit den Produkten des Unternehmens abwägen. Unabhängiger Rat kann eingeholt werden.</p>
      <p>ORO FINTECH LIMITED ist in den Seychellen unter der Registrierungsnummer 8425077-1 eingetragen und von der Finanzdienstleistungsbehörde (FSA) als Wertpapierhändler mit der Lizenznummer SD046 zugelassen.</p>`,
    es: `
      <p>Los productos apalancados como los CFD y Forex se consideran activos financieros complejos y pueden no ser adecuados para todos los inversores, ya que conllevan un alto grado de riesgo y pueden conducir a la pérdida de su inversión. Antes de involucrarse con el comercio, considere sus objetivos financieros, sus habilidades y evalúe los posibles riesgos asociados con el comercio de los Productos de la Compañía. Se puede buscar asesoramiento independiente.</p>
      <p>ORO Fintech Limited es una compañía financiera constituida y registrada bajo las leyes de la República de Seychelles con el número de registro 8425077-1 y autorizada por la Autoridad de Servicios Financieros (FSA) con el número de licencia SD046.</p>`,
    sv: `
      <p>Produkter med hävstång som CFD och Forex anses vara komplexa finansiella tillgångar och kanske inte är lämpliga för alla investerare eftersom de medför en hög risk och kan leda till förlust av din investering. Innan du engagerar dig i handel, överväg dina ekonomiska mål, dina färdigheter och bedöm de möjliga riskerna som är förknippade med att handla med företagets produkter. Också oberoende rådgivning kan sökas.</p>
      <p>ORO FINTECH LIMITED är registrerat på Seychellerna med registreringsnummer 8425077-1 och auktoriserat av Finansinspektionen (FSA) som värdepappershandlare med licensnummer SD046.</p>`,
    pt: `
      <p>Os produtos alavancados como CFDs e Forex são considerados ativos financeiros complexos e podem não ser adequados para todos os investidores, pois envolvem um alto grau de risco e podem levar à perda do seu investimento. Antes de se envolver no comércio, considere seus objetivos financeiros, suas habilidades e avalie os riscos potenciais associados ao comércio de Produtos da Empresa. O aconselhamento independente pode ser buscado.</p>
      <p>ORO FINTECH LIMITED está registrada nas Seicheles com o número de registro 8425077-1 e autorizada pela Autoridade de Serviços Financeiros (FSA) como Negociante de Valores Mobiliários com o número de licença SD046.</p>`,
    fi: `
      <p>Viputuotteet, kuten CFD:t ja Forex, ovat monimutkaisempia rahoitusvälineitä eivätkä välttämättä sovi kaikille sijoittajille, sillä ne sisältävät korkean riskin ja voivat johtaa sijoituksen menetykseen. Ennen kaupankäynnin aloittamista, harkitse taloudellisia tavoitteitasi, taitojasi ja arvioi kaupankäynnin mahdolliset riskit yrityksen tuotteilla. Voit pyytää itsenäistä neuvoa.</p>
      <p>ORO FINTECH LIMITED on rekisteröity Seychelleille rekisterinumero 8425077-1 ja se on valtuutettu Finanssivalvonnan (FSA) toimesta arvopaperinvälittäjäksi lisenssinumerolla SD046.</p>`,
    pl: `
      <p>Produkty dźwigniowe, takie jak CFD i Forex, są uważane za skomplikowane aktywa finansowe i mogą nie być odpowiednie dla wszystkich inwestorów, ponieważ wiążą się z wysokim ryzykiem i mogą prowadzić do utraty inwestycji. Zanim zaangażujesz się w handel, rozważ swoje cele finansowe, umiejętności oraz oceń możliwe ryzyko związane z handlem produktami firmy. Można skorzystać z niezależnej porady.</p>
      <p>ORO FINTECH LIMITED jest zarejestrowana na Seszelach pod numerem rejestracyjnym 8425077-1 i zatwierdzona przez Financial Services Authority (FSA) jako dealer papierów wartościowych z numerem licencji SD046.</p>`,
    hu: `
      <p>A tőkeáttételes termékek, mint a CFD-k és a Forex bonyolult pénzügyi eszközök, és nem biztos, hogy minden befektető számára megfelelőek, mivel magas kockázattal járnak, és elveszítheted a befektetésedet. Mielőtt elkezdenél kereskedni, fontold meg pénzügyi céljaidat, képességeidet, és mérlegeld a cég termékeivel való kereskedéshez kapcsolódó lehetséges kockázatokat. Független tanácsot is kérhetsz.</p>
      <p>ORO FINTECH LIMITED a Seychelle-szigeteken van bejegyezve a 8425077-1-es nyilvántartási számmal, és a Pénzügyi Szolgáltatások Hatósága (FSA) engedélyezte értékpapír-kereskedőként SD046-os engedélyszámmal.</p>`,
    th: `
      <p>ผลิตภัณฑ์ที่มีเลเวอเรจ เช่น CFD และ Forex ถือเป็นสินทรัพย์ทางการเงินที่ซับซ้อนและอาจไม่เหมาะสำหรับนักลงทุนทุกราย เนื่องจากมีความเสี่ยงสูงและอาจทำให้สูญเสียการลงทุนของคุณ ก่อนที่คุณจะเข้าร่วมการซื้อขาย โปรดพิจารณาวัตถุประสงค์ทางการเงินของคุณ ทักษะของคุณ และประเมินความเสี่ยงที่อาจเกิดขึ้นจากการซื้อขายผลิตภัณฑ์ของบริษัท อาจขอคำแนะนำจากผู้เชี่ยวชาญได้</p>
      <p>ORO FINTECH LIMITED ได้รับการจดทะเบียนในเซเชลส์โดยมีหมายเลขจดทะเบียน 8425077-1 และได้รับอนุญาตจากสำนักงานบริการทางการเงิน (FSA) ในฐานhผู้ค้า securities โดยมีหมายเลขใบอนุญาต SD046</p>`,
    ms: `
      <p>Produk leveraj seperti CFD dan Forex dianggap sebagai aset kewangan yang rumit dan mungkin tidak sesuai untuk semua pelabur kerana ia membawa risiko tinggi dan boleh menyebabkan kerugian pelaburan anda. Sebelum terlibat dalam perdagangan, pertimbangkan matlamat kewangan anda, kemahiran anda dan nilai risiko yang mungkin berkaitan dengan perdagangan Produk Syarikat. Nasihat bebas boleh dicari.</p>
      <p>ORO FINTECH LIMITED berdaftar di Seychelles dengan nombor pendaftaran 8425077-1 dan dibenarkan oleh Pihak Berkuasa Perkhidmatan Kewangan (FSA) sebagai Peniaga Sekuriti dengan nombor lesen SD046.</p>`,
    vi: `
      <p>Sản phẩm có đòn bẩy như CFDs và Forex được coi là tài sản tài chính phức tạp và có thể không phù hợp với tất cả các nhà đầu tư vì chúng mang lại rủi ro cao và có thể dẫn đến việc mất vốn đầu tư của bạn. Trước khi tham gia giao dịch, hãy xem xét mục tiêu tài chính, kỹ năng và đánh giá các rủi ro tiềm ẩn liên quan đến việc giao dịch Sản phẩm của Công ty. Có thể tìm kiếm lời khuyên độc lập.</p>
      <p>ORO FINTECH LIMITED được đăng ký tại Seychelles với số đăng ký 8425077-1 và được Ủy ban Dịch vụ Tài chính (FSA) cấp phép làm Nhà môi giới Chứng khoán với số giấy phép SD046.</p>`,
  };

  return {
    classic,
    esma,
    endorsed,
    outbrain: parasFooterOutbrain,
    atheneum: parasFooterAtheneum,
    rfm: parasFooterReadyForMail,
  };
}
