import type { BrandArrItem } from "../../types/brands";
import type { FXOROSVGVariation } from "../../types/brands/logo";
import type { TranslationsType } from "../../types/translations";
import { defaultLogo } from "./logos/defaultLogo";

export const fxoro = (
  whatsapp: boolean,
  whatsappNumber: () => TranslationsType
): BrandArrItem<FXOROSVGVariation> => ({
  id: 4,
  nameToLower: "fxoro",
  name: "FXORO",
  typage: {
    en: `https://my.fxoro.com/register`,
    it: `https://my.fxoro.com/it/registrati/`,
    tr: `https://my.fxoro25.com/tr/kayit-ol/`,
    ro: `https://my.fxoro.com/ro/inregistrare/`,
    ar: `https://my.fxoro.com/ar/%D8%AA%D8%B3%D8%AC%D9%8A%D9%84/`,
    de: `https://my.fxoro.com/de/registrieren/`,
    es: `https://my.fxoro.com/es/registrarse/`,
    sv: `https://my.fxoro.com/sv/registrera/`,
    pt: `https://my.fxoro.com/pt/registo/`,
    fi: `https://my.fxoro.com/fi/rekisteroidy/`,
    pl: `https://my.fxoro.com/pl/register/`,
    hu: `https://my.fxoro.com/hu/eles-szamlanyitas/`,
    th: `https://my.fxoro.com/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%A5%E0%B8%87%E0%B8%97%E0%B8%B0%E0%B9%80%E0%B8%9A-%E0%B8%A2%E0%B8%99/`,
    ms: `https://my.fxoro.com/ms/daftar/`,
    vi: `https://my.fxoro.com/vi/dang-ky/`,
  },
  recaptchaKey: "6LeuLYQjAAAAABfXp16faOgK81dNJOvm1otioobl",
  privacyLink: {
    en: `https://fxoro.com/en/privacy-and-security-policy/`,
    it: `https://fxoro.com/it/privacy-and-security-policy/`,
    tr: `https://fxoro.com/tr/privacy-and-security-policy/`,
    ro: `https://fxoro.com/ro/privacy-and-security-policy/`,
    ar: `https://fxoro.com/ar/privacy-and-security-policy/`,
    de: `https://fxoro.com/de/privacy-and-security-policy/`,
    es: `https://fxoro.com/es/privacy-and-security-policy/`,
    sv: `https://fxoro.com/sv/privacy-and-security-policy/`,
    pt: `https://fxoro.com/pt/privacy-and-security-policy/`,
    fi: `https://fxoro.com/fi/privacy-and-security-policy/`,
    pl: `https://fxoro.com/pl/privacy-and-security-policy/`,
    hu: `https://fxoro.com/hu/privacy-and-security-policy/`,
    th: `https://fxoro.com/th/privacy-and-security-policy/`,
    ms: `https://fxoro.com/ms/privacy-and-security-policy/`,
    vi: `https://fxoro.com/vi/privacy-and-security-policy/`,
  },
  whatsapp: whatsapp,
  whatsappNumber: whatsappNumber(),
  images: {
    logoSVG: {
      default: defaultLogo,
    },
    faviconLink: "https://fxoro.com/global_assets/imgs/favicon.svg",
  },
  officialTerms: {
    links: {
      privacyPolicy: {
        en: `https://fxoro.com/privacy-and-security-policy/`,
        it: `https://fxoro.com/it/privacy-and-security-policy/`,
        tr: `https://fxoro25.com/tr/privacy-and-security-policy/`,
        ro: `https://fxoro.com/ro/privacy-and-security-policy/`,
        ar: `https://fxoro.com/privacy-and-security-policy/`,
        de: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        es: `https://fxoro.com/es/privacy-and-security-policy/`,
        sv: `https://fxoro.com/sv/privacy-and-security-policy/`,
        pt: `https://fxoro.com/privacy-and-security-policy/`,
        fi: `https://fxoro.com/fi/privacy-and-security-policy/`,
        pl: `https://fxoro.com/pl/privacy-and-security-policy/`,
        hu: `https://fxoro.com/hu/privacy-and-security-policy/`,
        th: `https://fxoro.com/privacy-and-security-policy/`,
        ms: `https://fxoro.com/privacy-and-security-policy/`,
        vi: `https://fxoro.com/privacy-and-security-policy/`,
      },
      riskWarning: {
        en: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        it: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        tr: `https://fxoro25.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        ro: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        ar: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        de: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        es: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        sv: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        pt: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        fi: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        pl: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        hu: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        th: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        ms: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
        vi: `https://fxoro.com/wp-content/uploads/Risk_discolure_and_warning_notice.pdf`,
      },
      termsAndConditions: {
        en: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        it: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        tr: `https://fxoro25.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        ro: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        ar: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        de: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        es: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        sv: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        pt: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        fi: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        pl: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        hu: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        th: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        ms: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
        vi: `https://fxoro.com/wp-content/uploads/FXORO-Terms-and-conditions.pdf`,
      },
      orderExecutionPolicy: {
        en: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        it: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        tr: `https://fxoro25.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        ro: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        ar: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        de: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        es: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        sv: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        pt: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        fi: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        pl: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        hu: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        th: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        ms: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
        vi: `https://fxoro.com/wp-content/uploads/Order_Execution_Policy.pdf`,
      },
      costAndCharges: {
        en: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        it: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        tr: `https://fxoro25.com/wp-content/uploads/CostCharges.pdf`,
        ro: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        ar: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        de: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        es: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        sv: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        pt: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        fi: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        pl: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        hu: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        th: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        ms: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
        vi: `https://fxoro.com/wp-content/uploads/CostCharges.pdf`,
      },
    },
  },
});
