import type { BrandArrItem } from "../../types/brands";
import type { FXOROGlobalSVGVariation } from "../../types/brands/logo";
import type { TranslationsType } from "../../types/translations";
import {
  blackOrangeLogo,
  defaultLogo,
  whiteLogo,
  whiteOrangeLogo,
} from "./logos";

export const fxoro_global = ({
  whatsapp,
  whatsappNumber,
}: {
  whatsapp: boolean;
  whatsappNumber: () => TranslationsType;
}): BrandArrItem<FXOROGlobalSVGVariation> => ({
  nameToLower: "fxoro_global",
  name: "FXORO Global",
  typage: {
    en: `https://my.fxoroglobal.com/register`,
    it: ``,
    tr: ``,
    ro: `https://my.fxoroglobal.com/ro/inregistrare`,
    ar: `https://my.fxoroglobal.com/ar/%D8%AA%D8%B3%D8%AC%D9%8A%D9%84`,
    de: ``,
    es: `https://my.fxoroglobal.com/es/registrarse`,
    sv: ``,
    pt: ``,
    fi: ``,
    pl: ``,
    hu: ``,
    th: ``,
    ms: ``,
    vi: ``,
  },
  recaptchaKey: "6LeVlMcqAAAAABvFKKQ9jyh5zbSPyiIwcuiAF5eh",
  privacyLink: {
    en: `https://fxoroglobal.com/privacy-and-security/`,
    it: ``,
    tr: ``,
    ro: `https://fxoroglobal.com/ro/politica-de-securitate/`,
    ar: `https://fxoroglobal.com/ar/privacy-and-security-policy/`,
    de: ``,
    es: `https://fxoroglobal.com/es/politica-de-privacidad-y-seguridad/`,
    sv: ``,
    pt: ``,
    fi: ``,
    pl: ``,
    hu: ``,
    th: ``,
    ms: ``,
    vi: ``,
  },

  whatsapp: whatsapp,
  whatsappNumber: whatsappNumber(),
  images: {
    logoSVG: {
      default: defaultLogo,
      blackOrange: blackOrangeLogo,
      whiteOrange: whiteOrangeLogo,
      white: whiteLogo,
    },
    faviconLink: "https://fxoro.com/global_assets/imgs/favicon.svg",
  },
  officialTerms: {
    links: {
      privacyPolicy: {
        en: `https://fxoroglobal.com/en/privacy-and-security-policy/`,
        it: `https://fxoroglobal.com/it/privacy-and-security-policy/`,
        tr: `https://fxoroglobal.com/tr/privacy-and-security-policy/`,
        ro: `https://fxoroglobal.com/ro/politica-de-securitate/`,
        ar: `https://fxoroglobal.com/ar/privacy-and-security-policy/`,
        de: `https://fxoroglobal.com/de/privacy-and-security-policy/`,
        es: `https://fxoroglobal.com/es/politica-de-privacidad-y-seguridad/`,
        sv: `https://fxoroglobal.com/sv/privacy-and-security-policy/`,
        pt: `https://fxoroglobal.com/pt/privacy-and-security-policy/`,
        fi: `https://fxoroglobal.com/fi/privacy-and-security-policy/`,
        pl: `https://fxoroglobal.com/pl/privacy-and-security-policy/`,
        hu: `https://fxoroglobal.com/hu/privacy-and-security-policy/`,
        th: `https://fxoroglobal.com/th/privacy-and-security-policy/`,
        ms: `https://fxoroglobal.com/ms/privacy-and-security-policy/`,
        vi: `https://fxoroglobal.com/vi/privacy-and-security-policy/`,
      },
      riskWarning: {
        en: `https://fxoroglobal.com/risk-warning-notice-2/`,
        it: `https://fxoroglobal.com/it/risk-warning-notice/`,
        tr: `https://fxoroglobal.com/tr/risk-warning-notice/`,
        ro: `https://fxoroglobal.com/ro/avertisment-de-risc/`,
        ar: `https://fxoroglobal.com/ar/risk-warning-notice-2/`,
        de: `https://fxoroglobal.com/de/risk-warning-notice/`,
        es: `https://fxoroglobal.com/es/advertencia-de-riesgo/`,
        sv: `https://fxoroglobal.com/sv/risk-warning-notice/`,
        pt: `https://fxoroglobal.com/pt/risk-warning-notice/`,
        fi: `https://fxoroglobal.com/fi/risk-warning-notice/`,
        pl: `https://fxoroglobal.com/pl/risk-warning-notice/`,
        hu: `https://fxoroglobal.com/hu/risk-warning-notice/`,
        th: `https://fxoroglobal.com/th/risk-warning-notice/`,
        ms: `https://fxoroglobal.com/ms/risk-warning-notice/`,
        vi: `https://fxoroglobal.com/vi/risk-warning-notice/`,
      },
      termsAndConditions: {
        en: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        it: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        tr: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        ro: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        ar: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        de: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        es: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        sv: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        pt: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        fi: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        pl: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        hu: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        th: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        ms: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
        vi: `https://fxoroglobal.com/wp-content/uploads/2025/01/Client_s_Agreement.pdf`,
      },
      orderExecutionPolicy: {
        en: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        it: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        tr: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        ro: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        ar: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        de: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        es: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        sv: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        pt: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        fi: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        pl: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        hu: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        th: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        ms: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
        vi: `https://fxoroglobal.com/wp-content/uploads/2025/01/Order_Execution_Policy.pdf`,
      },
    },
  },
});
