import type { BrandArrItem } from "../../types/brands";
import type { FXOROGlobalSVGVariation } from "../../types/brands/logo";
import type { TranslationsType } from "../../types/translations";
import {
  blackOrangeLogo,
  defaultLogo,
  whiteLogo,
  whiteOrangeLogo,
} from "./logos";

export const fxoro_global = (
  whatsapp: boolean,
  whatsappNumber: () => TranslationsType
): BrandArrItem<FXOROGlobalSVGVariation> => ({
  id: 5,
  nameToLower: "fxoro_global",
  name: "FXORO Global",
  typage: {
    en: `https://my.global.fxoro.com/register`,
    it: `https://my.global.fxoro.com/it/registrati/`,
    tr: `https://my.global.fxoro25.com/tr/kayit-ol/`,
    ro: `https://my.global.fxoro.com/ro/inregistrare/`,
    ar: `https://my.global.fxoro.com/ar/%D8%AA%D8%B3%D8%AC%D9%8A%D9%84/`,
    de: `https://my.global.fxoro.com/de/registrieren/`,
    es: `https://my.global.fxoro.com/es/registrarse/`,
    sv: `https://my.global.fxoro.com/sv/registrera/`,
    pt: `https://my.global.fxoro.com/pt/registo/`,
    fi: `https://my.global.fxoro.com/fi/rekisteroidy/`,
    pl: `https://my.global.fxoro.com/pl/register/`,
    hu: `https://my.global.fxoro.com/hu/eles-szamlanyitas/`,
    th: `https://my.global.fxoro.com/th/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%A5%E0%B8%87%E0%B8%97%E0%B8%B0%E0%B9%80%E0%B8%9A-%E0%B8%A2%E0%B8%99/`,
    ms: `https://my.global.fxoro.com/ms/daftar/`,
    vi: `https://my.global.fxoro.com/vi/dang-ky/`,
  },
  recaptchaKey: "6LeILoQjAAAAAN_Dsbeu4ncn9Adut_tO3uK4Blnk", // new for fxoroglobal.com 6LeVlMcqAAAAABvFKKQ9jyh5zbSPyiIwcuiAF5eh
  privacyLink: {
    en: `https://global.fxoro.com/en/privacy-and-security-policy/`,
    it: `https://global.fxoro.com/it/privacy-and-security-policy/`,
    tr: `https://global.fxoro.com/tr/privacy-and-security-policy/`,
    ro: `https://global.fxoro.com/ro/privacy-and-security-policy/`,
    ar: `https://global.fxoro.com/ar/privacy-and-security-policy/`,
    de: `https://global.fxoro.com/de/privacy-and-security-policy/`,
    es: `https://global.fxoro.com/es/privacy-and-security-policy/`,
    sv: `https://global.fxoro.com/sv/privacy-and-security-policy/`,
    pt: `https://global.fxoro.com/pt/privacy-and-security-policy/`,
    fi: `https://global.fxoro.com/fi/privacy-and-security-policy/`,
    pl: `https://global.fxoro.com/pl/privacy-and-security-policy/`,
    hu: `https://global.fxoro.com/hu/privacy-and-security-policy/`,
    th: `https://global.fxoro.com/th/privacy-and-security-policy/`,
    ms: `https://global.fxoro.com/ms/privacy-and-security-policy/`,
    vi: `https://global.fxoro.com/vi/privacy-and-security-policy/`,
  },

  whatsapp: whatsapp,
  whatsappNumber: whatsappNumber(),
  images: {
    logoSVG: {
      default: defaultLogo,
      blackOrange: blackOrangeLogo,
      whiteOrange: whiteOrangeLogo,
      white: whiteLogo,
    },
    faviconLink: "https://fxoro.com/global_assets/imgs/favicon.svg",
  },
  officialTerms: {
    links: {
      privacyPolicy: {
        en: `https://global.fxoro.com/en/privacy-and-security-policy/`,
        it: `https://global.fxoro.com/it/privacy-and-security-policy/`,
        tr: `https://global.fxoro.com/tr/privacy-and-security-policy/`,
        ro: `https://global.fxoro.com/ro/privacy-and-security-policy/`,
        ar: `https://global.fxoro.com/ar/privacy-and-security-policy/`,
        de: `https://global.fxoro.com/de/privacy-and-security-policy/`,
        es: `https://global.fxoro.com/es/privacy-and-security-policy/`,
        sv: `https://global.fxoro.com/sv/privacy-and-security-policy/`,
        pt: `https://global.fxoro.com/pt/privacy-and-security-policy/`,
        fi: `https://global.fxoro.com/fi/privacy-and-security-policy/`,
        pl: `https://global.fxoro.com/pl/privacy-and-security-policy/`,
        hu: `https://global.fxoro.com/hu/privacy-and-security-policy/`,
        th: `https://global.fxoro.com/th/privacy-and-security-policy/`,
        ms: `https://global.fxoro.com/ms/privacy-and-security-policy/`,
        vi: `https://global.fxoro.com/vi/privacy-and-security-policy/`,
      },
      riskWarning: {
        en: `https://global.fxoro.com/en/risk-warning-notice/`,
        it: `https://global.fxoro.com/it/risk-warning-notice/`,
        tr: `https://global.fxoro.com/tr/risk-warning-notice/`,
        ro: `https://global.fxoro.com/ro/risk-warning-notice/`,
        ar: `https://global.fxoro.com/ar/risk-warning-notice/`,
        de: `https://global.fxoro.com/de/risk-warning-notice/`,
        es: `https://global.fxoro.com/es/risk-warning-notice/`,
        sv: `https://global.fxoro.com/sv/risk-warning-notice/`,
        pt: `https://global.fxoro.com/pt/risk-warning-notice/`,
        fi: `https://global.fxoro.com/fi/risk-warning-notice/`,
        pl: `https://global.fxoro.com/pl/risk-warning-notice/`,
        hu: `https://global.fxoro.com/hu/risk-warning-notice/`,
        th: `https://global.fxoro.com/th/risk-warning-notice/`,
        ms: `https://global.fxoro.com/ms/risk-warning-notice/`,
        vi: `https://global.fxoro.com/vi/risk-warning-notice/`,
      },
      termsAndConditions: {
        en: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        it: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        tr: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        ro: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        ar: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        de: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        es: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        sv: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        pt: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        fi: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        pl: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        hu: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        th: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        ms: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
        vi: `https://global.fxoro.com/wp-content/uploads/2020/02/Client_s_Agreement.pdf`,
      },
      orderExecutionPolicy: {
        en: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        it: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        tr: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        ro: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        ar: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        de: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        es: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        sv: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        pt: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        fi: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        pl: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        hu: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        th: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        ms: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
        vi: `https://global.fxoro.com/wp-content/uploads/2020/02/Order_Execution_Policy.pdf`,
      },
    },
  },
});
