import type { TranslationsType } from "../../../types/translations";

export const parasFooterAtheneum: TranslationsType = {
  en: `<p>The company provides financial education services in collaboration with third party providers. For more information please consult the <a target="_blank" href="/privacypolicy/en/"><strong>Privacy Policy</strong></a>. We do not offer investment advice or financial products. All information is educational purposes only.</p><p>This website is property of Trading Atheneum. ${new Date().getFullYear()} All Rights Reserved.</p>`,
  it: `<p>L'azienda fornisce servizi di educazione finanziaria in collaborazione con fornitori terzi. Per maggiori informazioni, si prega di consultare <a target="_blank" href="/privacypolicy/it/"><strong>l'Informativa sulla Privacy</strong></a>. Non offriamo consulenza sugli investimenti né prodotti finanziari. Tutte le informazioni sono esclusivamente a scopo educativo.</p><p>Questo sito web è di proprietà di Trading Atheneum. ${new Date().getFullYear()} Tutti i diritti riservati.</p>`,
  tr: `<p>Şirket, üçüncü taraf sağlayıcılarla işbirliği içinde finansal eğitim hizmetleri sunmaktadır. Daha fazla bilgi için lütfen <a target="_blank" href="/privacypolicy/tr/"><strong>Gizlilik Politikası</strong></a>'nı inceleyin. Yatırım tavsiyesi veya finansal ürünler sunmuyoruz. Tüm bilgiler yalnızca eğitim amaçlıdır.</p><p>Bu web sitesi Trading Atheneum'a aittir. ${new Date().getFullYear()} Tüm Hakları Saklıdır.</p>`,
  ro: `<p>Compania oferă servicii de educație financiară în colaborare cu furnizori terți. Pentru mai multe informații, vă rugăm să consultați <a target="_blank" href="/privacypolicy/ro/"><strong>Politica de Confidențialitate</strong></a>. Nu oferim consultanță în investiții sau produse financiare. Toate informațiile sunt doar în scop educațional.</p><p>Acest site web este proprietatea Trading Atheneum. ${new Date().getFullYear()} Toate drepturile rezervate.</p>`,
  ar: `<p>توفر الشركة خدمات التعليم المالي بالتعاون مع مزودي الطرف الثالث. للحصول على مزيد من المعلومات، يرجى استشارة <a target="_blank" href="/privacypolicy/ar/"><strong>سياسة الخصوصية</strong></a>. نحن لا نقدم نصائح استثمارية أو منتجات مالية. جميع المعلومات هي لأغراض تعليمية فقط.</p><p>موقع الويب هذا هو ملك لشركة Trading Atheneum. ${new Date().getFullYear()} جميع الحقوق محفوظة.</p>`,
  de: `<p>Das Unternehmen bietet in Zusammenarbeit mit Drittanbietern Finanzbildungsdienste an. Weitere Informationen finden Sie in der <a target="_blank" href="/privacypolicy/de/"><strong>Datenschutzerklärung</strong></a>. Wir bieten keine Anlageberatung oder Finanzprodukte an. Alle Informationen dienen nur zu Bildungszwecken.</p><p>Diese Website ist Eigentum von Trading Atheneum. ${new Date().getFullYear()} Alle Rechte vorbehalten.</p>`,
  es: `<p>La empresa ofrece servicios de educación financiera en colaboración con proveedores externos. Para obtener más información, consulte la <a target="_blank" href="/privacypolicy/es/"><strong>Política de Privacidad</strong></a>. No ofrecemos asesoramiento de inversión ni productos financieros. Toda la información es solo para fines educativos.</p><p>Este sitio web es propiedad de Trading Atheneum. ${new Date().getFullYear()} Todos los derechos reservados.</p>`,
  sv: `<p>Företaget erbjuder finansiella utbildningstjänster i samarbete med tredjepartsleverantörer. För mer information, vänligen konsultera <a target="_blank" href="/privacypolicy/sv/"><strong>Integritetspolicy</strong></a>. Vi erbjuder inte investeringsrådgivning eller finansiella produkter. All information är endast avsedd för utbildningsändamål.</p><p>Denna webbplats tillhör Trading Atheneum. ${new Date().getFullYear()} Alla rättigheter reserverade.</p>`,
  pt: `<p>A empresa oferece serviços de educação financeira em colaboração com prestadores de serviços terceirizados. Para mais informações, consulte a <a target="_blank" href="/privacypolicy/pt/"><strong>Política de Privacidade</strong></a>. Não oferecemos aconselhamento de investimentos ou produtos financeiros. Todas as informações são apenas para fins educativos.</p><p>Este site é propriedade da Trading Atheneum. ${new Date().getFullYear()} Todos os direitos reservados.</p>`,
  fi: `<p>Yritys tarjoaa talouskoulutuspalveluja yhteistyössä kolmansien osapuolten tarjoajien kanssa. Lisätietoja varten tutustu <a target="_blank" href="/privacypolicy/fi/"><strong>Tietosuojakäytäntöön</strong></a>. Emme tarjoa sijoitusneuvontaa tai rahoitustuotteita. Kaikki tiedot ovat vain koulutustarkoituksessa.</p><p>Tämä verkkosivusto on Trading Atheneumin omaisuus. ${new Date().getFullYear()} Kaikki oikeudet pidätetään.</p>`,
  pl: `<p>Firma oferuje usługi edukacji finansowej we współpracy z dostawcami zewnętrznymi. Aby uzyskać więcej informacji, zapoznaj się z <a target="_blank" href="/privacypolicy/pl/"><strong>Polityką prywatności</strong></a>. Nie udzielamy porad inwestycyjnych ani nie oferujemy produktów finansowych. Wszystkie informacje mają wyłącznie charakter edukacyjny.</p><p>Ta strona internetowa jest własnością Trading Atheneum. ${new Date().getFullYear()} Wszelkie prawa zastrzeżone.</p>`,
  hu: `<p>A cég pénzügyi oktatási szolgáltatásokat nyújt harmadik féltől származó szolgáltatókkal együttműködve. További információkért kérjük, olvassa el az <a target="_blank" href="/privacypolicy/hu/"><strong>Adatvédelmi irányelvek</strong></a> oldalt. Nem nyújtunk befektetési tanácsokat vagy pénzügyi termékeket. Minden információ kizárólag oktatási célokra szolgál.</p><p>Ez a webhely a Trading Atheneum tulajdona. ${new Date().getFullYear()} Minden jog fenntartva.</p>`,
  th: `<p>บริษัทให้บริการการศึกษาทางการเงินร่วมกับผู้ให้บริการภายนอก สำหรับข้อมูลเพิ่มเติมโปรดดูที่ <a target="_blank" href="/privacypolicy/th/"><strong>นโยบายความเป็นส่วนตัว</strong></a>. เราไม่ให้คำแนะนำการลงทุนหรือผลิตภัณฑ์ทางการเงิน ข้อมูลทั้งหมดใช้เพื่อการศึกษาตามวัตถุประสงค์เท่านั้น.</p><p>เว็บไซต์นี้เป็นทรัพย์สินของ Trading Atheneum. ${new Date().getFullYear()} สงวนลิขสิทธิ์.</p>`,
  ms: `<p>Syarikat menyediakan perkhidmatan pendidikan kewangan dengan kerjasama penyedia pihak ketiga. Untuk maklumat lanjut, sila rujuk <a target="_blank" href="/privacypolicy/ms/"><strong>Dasar Privasi</strong></a>. Kami tidak menawarkan nasihat pelaburan atau produk kewangan. Semua maklumat adalah untuk tujuan pendidikan sahaja.</p><p>Laman web ini adalah milik Trading Atheneum. ${new Date().getFullYear()} Semua Hak Cipta Terpelihara.</p>`,
  vi: `<p>Công ty cung cấp dịch vụ giáo dục tài chính hợp tác với các nhà cung cấp bên thứ ba. Để biết thêm thông tin, vui lòng tham khảo <a target="_blank" href="/privacypolicy/vi/"><strong>Chính Sách Bảo Mật</strong></a>. Chúng tôi không cung cấp tư vấn đầu tư hoặc sản phẩm tài chính. Tất cả thông tin chỉ nhằm mục đích giáo dục.</p><p>Trang web này là tài sản của Trading Atheneum. ${new Date().getFullYear()} Bảo lưu tất cả quyền.</p>`,
  showcase: `<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus <a target="_blank" href="/privacypolicy/en/"><strong>elementum semper</strong></a> nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>`,
};
