import type { TranslationsType } from "../../../types/translations";

export const parasFooterReadyForMail: TranslationsType = {
  en: `<p>Material presented including access to educational courses are provided for informative purposes only and in order to enhance knowledge and familiarity with such concepts. No guarantees or assurances are in no way given and any information offered shall be cross-checked against other reliable sources. Read our <a target="_blank" href="/privacypolicy/rfm/en/"><strong>Privacy Policy</strong></a> to learn how we protect your information.</p>`,
  it: `<p>Il materiale presentato, incluso l'accesso ai corsi educativi, è fornito solo a scopo informativo e per migliorare la conoscenza e la familiarità con tali concetti. Non vengono fornite garanzie o assicurazioni e qualsiasi informazione offerta verrà verificata con altre fonti affidabili. Leggi la nostra <a target="_blank" href="/privacypolicy/rfm/it/"><strong>Politica sulla privacy</strong></a> per sapere come proteggiamo le tue informazioni.</p>`,
  tr: `<p>Sunulan materyaller, eğitim kurslarına erişim dahil, yalnızca bilgilendirme amacıyla ve bu tür kavramlara dair bilgi ve aşinalığı artırmak amacıyla sağlanmaktadır. Hiçbir şekilde garanti veya teminat verilmez ve sunulan her türlü bilgi, diğer güvenilir kaynaklarla doğrulanacaktır. Bilgilerinizi nasıl koruduğumuzu öğrenmek için <a target="_blank" href="/privacypolicy/rfm/tr/"><strong>Gizlilik Politikamızı</strong></a> okuyun.</p>`,
  ro: `<p>Materialele prezentate, inclusiv accesul la cursuri educaționale, sunt furnizate doar în scop informativ și pentru a îmbunătăți cunoștințele și familiarizarea cu astfel de concepte. Nu se oferă în niciun fel garanții sau asigurări și orice informație oferită va fi verificată cu alte surse de încredere. Citiți <a target="_blank" href="/privacypolicy/rfm/ro/"><strong>Politica noastră de confidențialitate</strong></a> pentru a afla cum vă protejăm informațiile.</p>`,
  ar: `<p>المواد المعروضة بما في ذلك الوصول إلى الدورات التعليمية مقدمة لأغراض إعلامية فقط ولزيادة المعرفة والألفة مع هذه المفاهيم. لا يتم تقديم أي ضمانات أو تأكيدات من أي نوع وسيتم التحقق من أي معلومات مقدمة مع مصادر موثوقة أخرى. اقرأ <a target="_blank" href="/privacypolicy/rfm/ar/"><strong>سياسة الخصوصية</strong></a> لدينا لمعرفة كيفية حماية معلوماتك.</p>`,
  de: `<p>Das präsentierte Material, einschließlich des Zugriffs auf Bildungsangebote, wird nur zu Informationszwecken bereitgestellt, um das Wissen und das Verständnis für solche Konzepte zu fördern. Es werden keine Garantien oder Zusicherungen gegeben und alle angebotenen Informationen werden mit anderen zuverlässigen Quellen abgeglichen. Lesen Sie unsere <a target="_blank" href="/privacypolicy/rfm/de/"><strong>Datenschutzrichtlinie</strong></a>, um zu erfahren, wie wir Ihre Informationen schützen.</p>`,
  es: `<p>El material presentado, incluido el acceso a cursos educativos, se proporciona únicamente con fines informativos y para mejorar el conocimiento y la familiaridad con dichos conceptos. No se ofrecen garantías ni seguridades de ninguna manera y cualquier información ofrecida se comparará con otras fuentes confiables. Lea nuestra <a target="_blank" href="/privacypolicy/rfm/es/"><strong>Política de Privacidad</strong></a> para saber cómo protegemos su información.</p>`,
  sv: `<p>Det presenterade materialet, inklusive tillgång till utbildningskurser, tillhandahålls endast för informationsändamål och för att förbättra kunskap och kännedom om sådana koncept. Inga garantier eller försäkringar ges och all information som erbjuds kommer att dubbelkollas med andra pålitliga källor. Läs vår <a target="_blank" href="/privacypolicy/rfm/sv/"><strong>Integritetspolicy</strong></a> för att ta reda på hur vi skyddar din information.</p>`,
  pt: `<p>Os materiais apresentados, incluindo o acesso a cursos educativos, são fornecidos apenas para fins informativos e para melhorar o conhecimento e a familiaridade com tais conceitos. Não são oferecidas garantias ou assegurações de qualquer tipo, e qualquer informação oferecida será verificada com outras fontes confiáveis. Leia nossa <a target="_blank" href="/privacypolicy/rfm/pt/"><strong>Política de Privacidade</strong></a> para saber como protegemos suas informações.</p>`,
  fi: `<p>Esitetyt materiaalit, mukaan lukien pääsy koulutuskursseille, tarjotaan vain tiedotustarkoituksiin ja jotta parannetaan tietämystä ja perehtyneisyyttä näihin käsitteisiin. Ei anneta takeita tai vakuuksia, ja tarjottu tieto tarkistetaan muista luotettavista lähteistä. Lue meidän <a target="_blank" href="/privacypolicy/rfm/fi/"><strong>Tietosuojakäytännöt</strong></a> oppiaksesi, miten suojaamme tietosi.</p>`,
  pl: `<p>Prezentowane materiały, w tym dostęp do kursów edukacyjnych, są dostarczane wyłącznie w celach informacyjnych oraz w celu poszerzenia wiedzy i zaznajomienia z takimi pojęciami. Nie udziela się żadnych gwarancji ani zapewnień, a wszelkie oferowane informacje będą weryfikowane z innymi wiarygodnymi źródłami. Przeczytaj naszą <a target="_blank" href="/privacypolicy/rfm/pl/"><strong>Politykę prywatności</strong></a>, aby dowiedzieć się, jak chronimy Twoje informacje.</p>`,
  hu: `<p>A bemutatott anyagok, beleértve az oktatási tanfolyamokhoz való hozzáférést, csak tájékoztatási céllal és az ilyen fogalmak megismerésének és megértésének javítása érdekében kerülnek bemutatásra. Semmilyen garanciát vagy biztosítékot nem adunk, és minden felajánlott információt más megbízható forrásokkal fogunk ellenőrizni. Olvassa el adatvédelmi szabályzatunkat <a target="_blank" href="/privacypolicy/rfm/hu/"><strong>adatvédelmi szabályzatunkat</strong></a> a személyes adataid védelmének módjáról.</p>`,
  th: `<p>วัสดุที่นำเสนอรวมถึงการเข้าถึงหลักสูตรการศึกษานั้นจัดทำขึ้นเพื่อวัตถุประสงค์ในการให้ข้อมูลเท่านั้นและเพื่อเพิ่มพูนความรู้และความคุ้นเคยกับแนวคิดดังกล่าว ไม่มีการให้การรับประกันหรือการรับรองใด ๆ และข้อมูลที่มีการให้จะได้รับการตรวจสอบกับแหล่งข้อมูลที่เชื่อถือได้ โปรดอ่าน <a target="_blank" href="/privacypolicy/rfm/th/"><strong>นโยบายความเป็นส่วนตัว</strong></a> ของเราเพื่อเรียนรู้วิธีที่เราปกป้องข้อมูลของคุณ</p>`,
  ms: `<p>Bahan yang dipersembahkan termasuk akses kepada kursus pendidikan disediakan untuk tujuan maklumat sahaja dan untuk meningkatkan pengetahuan dan kefahaman mengenai konsep-konsep tersebut. Tiada jaminan atau kepastian diberikan dan sebarang maklumat yang ditawarkan akan disemak dengan sumber yang boleh dipercayai. Baca <a target="_blank" href="/privacypolicy/rfm/ms/"><strong>Dasar Privasi</strong></a> kami untuk mengetahui bagaimana kami melindungi maklumat anda.</p>`,
  vi: `<p>Vật liệu được trình bày, bao gồm quyền truy cập vào các khóa học giáo dục, chỉ được cung cấp cho mục đích thông tin và để nâng cao kiến thức và sự quen thuộc với những khái niệm này. Không có bất kỳ sự đảm bảo hay cam kết nào được đưa ra và bất kỳ thông tin nào cung cấp sẽ được kiểm tra lại với các nguồn đáng tin cậy khác. Đọc <a target="_blank" href="/privacypolicy/rfm/vi/"><strong>Chính sách bảo mật</strong></a> của chúng tôi để biết cách chúng tôi bảo vệ thông tin của bạn.</p>`,
};
