import { type TranslationsType } from "../../../types/translations";

export const parasFooterOutbrain: TranslationsType = {
  en: `<p>CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. The vast majority of retail investor accounts lose money when trading CFDs. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.</p>`,
  it: `<p>I CFD sono strumenti complessi e comportano un alto rischio di perdere rapidamente denaro a causa della leva finanziaria. La stragrande maggioranza degli account degli investitori al dettaglio perde denaro quando opera con i CFD. Devi considerare se comprendi come funzionano i CFD e se puoi permetterti di assumere l'alto rischio di perdere il tuo denaro.</p>`,
  tr: `<p>CFD'ler karmaşık araçlardır ve kaldıraç nedeniyle hızla para kaybetme riski taşır. Perakende yatırımcı hesaplarının büyük bir kısmı CFD ticareti yaparken para kaybeder. CFD'lerin nasıl çalıştığını anlayıp anlamadığınızı ve paranızı kaybetme yüksek riskini göze alıp alamayacağınızı düşünmelisiniz.</p>`,
  ro: `<p>CFD-urile sunt instrumente complexe și vin cu un risc ridicat de pierdere rapidă a banilor din cauza levierului. Marea majoritate a conturilor de investitori retail pierd bani atunci când tranzacționează CFD-uri. Ar trebui să luați în considerare dacă înțelegeți cum funcționează CFD-urile și dacă vă permiteți să asumați riscul ridicat de a vă pierde banii.</p>`,
  ar: `<p>عقود الفروقات هي أدوات معقدة وتنطوي على خطر كبير في فقدان الأموال بسرعة بسبب الرافعة المالية. تفقد الغالبية العظمى من حسابات المستثمرين الأفراد الأموال عند تداول عقود الفروقات. يجب عليك أن تأخذ في اعتبارك ما إذا كنت تفهم كيفية عمل عقود الفروقات وما إذا كان بإمكانك تحمل المخاطر العالية لفقدان أموالك.</p>`,
  de: `<p>CFDs sind komplexe Instrumente und bergen ein hohes Risiko, aufgrund der Hebelwirkung schnell Geld zu verlieren. Die überwältigende Mehrheit der Einzelhandelskundenkonten verliert Geld beim Handel mit CFDs. Sie sollten überlegen, ob Sie verstehen, wie CFDs funktionieren, und ob Sie sich den hohen Risikos eines Verlusts Ihres Geldes leisten können.</p>`,
  es: `<p>Los CFDs son instrumentos complejos y conllevan un alto riesgo de perder dinero rápidamente debido al apalancamiento. La gran mayoría de las cuentas de inversores minoristas pierden dinero cuando operan con CFDs. Debe considerar si comprende cómo funcionan los CFDs y si puede permitirse asumir el alto riesgo de perder su dinero.</p>`,
  sv: `<p>CFD:er är komplexa instrument och innebär en hög risk att förlora pengar snabbt på grund av hävstångseffekt. Den största delen av detaljhandelsinvesterares konton förlorar pengar när de handlar med CFD:er. Du bör överväga om du förstår hur CFD:er fungerar och om du har råd att ta den höga risken att förlora dina pengar.</p>`,
  pt: `<p>Os CFDs são instrumentos complexos e apresentam um alto risco de perder dinheiro rapidamente devido à alavancagem. A grande maioria das contas de investidores de varejo perde dinheiro ao negociar CFDs. Você deve considerar se entende como os CFDs funcionam e se pode arcar com o alto risco de perder seu dinheiro.</p>`,
  fi: `<p>CFD:t ovat monimutkaisia välineitä, ja ne sisältävät suuren riskin rahojen nopeasta menettämisestä vipuvaikutuksen vuoksi. Suurin osa yksityissijoittajatilistä menettää rahaa CFD-kaupankäynnissä. Sinun tulisi harkita, ymmärrätkö, miten CFD:t toimivat, ja voitko kestää suuren riskin menettää rahasi.</p>`,
  pl: `<p>CFD to złożone instrumenty finansowe i wiążą się z wysokim ryzykiem szybkiej utraty pieniędzy z powodu dźwigni. Większość kont inwestorów detalicznych traci pieniądze podczas handlu CFD. Powinieneś rozważyć, czy rozumiesz, jak działają CFD i czy możesz pozwolić sobie na podjęcie wysokiego ryzyka utraty pieniędzy.</p>`,
  hu: `<p>A CFD-k bonyolulták és magas kockázattal járnak, mivel gyorsan elveszítheted pénzedet a tőkeáttétel miatt. A kiskereskedelmi befektetők többsége pénzt veszít a CFD-kkel való kereskedés során. Fontolóra kell venned, hogy érted-e, hogyan működnek a CFD-k, és hogy megengedheted-e magadnak, hogy vállald a pénzed gyors elvesztésének magas kockázatát.</p>`,
  th: `<p>CFD เป็นเครื่องมือที่ซับซ้อนและมีความเสี่ยงสูงในการสูญเสียเงินอย่างรวดเร็วเนื่องจากเลเวอเรจ นักลงทุนรายย่อยส่วนใหญ่สูญเสียเงินเมื่อทำการซื้อขาย CFD คุณควรพิจารณาว่าคุณเข้าใจวิธีการทำงานของ CFD หรือไม่ และคุณสามารถรับความเสี่ยงสูงในการสูญเสียเงินได้หรือไม่</p>`,
  ms: `<p>CFD adalah instrumen yang kompleks dan membawa risiko tinggi untuk kehilangan wang dengan cepat kerana penggunaan leveraj. Kebanyakan akaun pelabur runcit kehilangan wang apabila berdagang CFD. Anda harus mempertimbangkan sama ada anda memahami bagaimana CFD berfungsi dan sama ada anda mampu untuk mengambil risiko tinggi kehilangan wang anda.</p>`,
  vi: `<p>CFD là công cụ phức tạp và mang lại rủi ro cao về việc mất tiền nhanh chóng do đòn bẩy. Phần lớn các tài khoản nhà đầu tư bán lẻ mất tiền khi giao dịch CFD. Bạn nên xem xét liệu bạn có hiểu cách CFD hoạt động và liệu bạn có thể chấp nhận rủi ro cao khi mất tiền hay không.</p>`,
  showcase: `<p>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>`,
};
